#!/bin/bash
my_shell=`cat /etc/passwd | grep $USER | cut -d: -f7`
for usershell in $( cat /etc/passwd | cut -d: -f1,7 ) ; do
    user=`echo "$usershell" | cut -d: -f1`
    shell=`echo "$usershell" | cut -d: -f2`
    case $shell in 
       $my_shell) 
            echo change password for $user
            passwd $user
           ;;
        *) ;;
    esac ;
done
