#!/bin/bash

for usershell in $( cat /etc/passwd | cut -d: -f1,7 ) ; do
    user=`echo "$usershell" | cut -d: -f1`
    shell=`echo "$usershell" | cut -d: -f2`
    case $shell in 
       /bin/bash) 
            echo change passord for $user
            passwd $user
           ;;
        *) ;;
    esac ;
done
